package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJuzi<M extends BaseJuzi<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setPublish(java.lang.Integer publish) {
		set("publish", publish);
	}
	
	public java.lang.Integer getPublish() {
		return getInt("publish");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setLength(java.lang.Integer length) {
		set("length", length);
	}
	
	public java.lang.Integer getLength() {
		return getInt("length");
	}

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}
	
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public void setFrom(java.lang.String from) {
		set("from", from);
	}
	
	public java.lang.String getFrom() {
		return getStr("from");
	}

	public void setCategory(java.lang.String category) {
		set("category", category);
	}
	
	public java.lang.String getCategory() {
		return getStr("category");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}
	
	public java.lang.String getTags() {
		return getStr("tags");
	}

	public void setApplyDesc(java.lang.String applyDesc) {
		set("applyDesc", applyDesc);
	}
	
	public java.lang.String getApplyDesc() {
		return getStr("applyDesc");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("updateAt", updateAt);
	}
	
	public java.util.Date getUpdateAt() {
		return get("updateAt");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
	}
	
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

	public void setAccountAt(java.lang.Integer accountAt) {
		set("accountAt", accountAt);
	}
	
	public java.lang.Integer getAccountAt() {
		return getInt("accountAt");
	}

}
