package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseJuzi;
import com.juzicool.search.JuziObject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Juzi extends BaseJuzi<Juzi> implements JuziObject {
    public static final int PUBLIC_REVIEW = 0;    // 待审核
    public static final int PUBLIC_OK = 1;    // 已发布
    
    
    
}
