package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BasePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {
	
}
